services:
- type: web
  name: dash-app
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn src.app:server --log-file=-
  healthCheckPath: /
  envVars:
  - key: PROJECT_ID
    value: maps-407800
  - key: SECRET_ID
    value: google-api-key
  - key: VERSION_ID
    value: latest
